# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from db import db_pb2 as db_dot_protobuff_dot_db__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in db/protobuff/db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class dbStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNewCard = channel.unary_unary(
                '/db/CreateNewCard',
                request_serializer=db_dot_protobuff_dot_db__pb2.DBRequestCreateNewCard.SerializeToString,
                response_deserializer=db_dot_protobuff_dot_db__pb2.DBResponseCreateNewCard.FromString,
                _registered_method=True)
        self.GetCard = channel.unary_unary(
                '/db/GetCard',
                request_serializer=db_dot_protobuff_dot_db__pb2.DBRequestGetCard.SerializeToString,
                response_deserializer=db_dot_protobuff_dot_db__pb2.DBResponseGetCard.FromString,
                _registered_method=True)


class dbServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNewCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_dbServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNewCard': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNewCard,
                    request_deserializer=db_dot_protobuff_dot_db__pb2.DBRequestCreateNewCard.FromString,
                    response_serializer=db_dot_protobuff_dot_db__pb2.DBResponseCreateNewCard.SerializeToString,
            ),
            'GetCard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCard,
                    request_deserializer=db_dot_protobuff_dot_db__pb2.DBRequestGetCard.FromString,
                    response_serializer=db_dot_protobuff_dot_db__pb2.DBResponseGetCard.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'db', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('db', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class db(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNewCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/db/CreateNewCard',
            db_dot_protobuff_dot_db__pb2.DBRequestCreateNewCard.SerializeToString,
            db_dot_protobuff_dot_db__pb2.DBResponseCreateNewCard.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/db/GetCard',
            db_dot_protobuff_dot_db__pb2.DBRequestGetCard.SerializeToString,
            db_dot_protobuff_dot_db__pb2.DBResponseGetCard.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
