# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db/protobuff/db.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64\x62/protobuff/db.proto\"D\n\x16\x44\x42RequestCreateNewCard\x12\r\n\x05Label\x18\x01 \x01(\t\x12\r\n\x05Price\x18\x02 \x01(\x02\x12\x0c\n\x04\x44\x61ta\x18\x03 \x01(\t\"C\n\x17\x44\x42ResponseCreateNewCard\x12\x0e\n\x06Status\x18\x01 \x01(\x05\x12\n\n\x02Id\x18\x02 \x01(\x05\x12\x0c\n\x04Hash\x18\x03 \x01(\t\"\x1e\n\x10\x44\x42RequestGetCard\x12\n\n\x02Id\x18\x01 \x01(\x05\"O\n\x11\x44\x42ResponseGetCard\x12\x0e\n\x06Status\x18\x01 \x01(\x05\x12\r\n\x05Label\x18\x02 \x01(\t\x12\r\n\x05Price\x18\x03 \x01(\x02\x12\x0c\n\x04\x44\x61ta\x18\x04 \x01(\t2z\n\x02\x64\x62\x12\x42\n\rCreateNewCard\x12\x17.DBRequestCreateNewCard\x1a\x18.DBResponseCreateNewCard\x12\x30\n\x07GetCard\x12\x11.DBRequestGetCard\x1a\x12.DBResponseGetCardb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'db.protobuff.db_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DBREQUESTCREATENEWCARD']._serialized_start=25
  _globals['_DBREQUESTCREATENEWCARD']._serialized_end=93
  _globals['_DBRESPONSECREATENEWCARD']._serialized_start=95
  _globals['_DBRESPONSECREATENEWCARD']._serialized_end=162
  _globals['_DBREQUESTGETCARD']._serialized_start=164
  _globals['_DBREQUESTGETCARD']._serialized_end=194
  _globals['_DBRESPONSEGETCARD']._serialized_start=196
  _globals['_DBRESPONSEGETCARD']._serialized_end=275
  _globals['_DB']._serialized_start=277
  _globals['_DB']._serialized_end=399
# @@protoc_insertion_point(module_scope)
